name: Generate Open Badge
true:
  workflow_dispatch:
    inputs:
      badge_id:
        description: Select the badge
        required: true
        type: choice
        options:
        - beta-tester
        - contributor-2024
      recipient_email:
        description: Recipient's Email
        required: true
        type: string
      evidence_url:
        description: URL to evidence of achievement (e.g., PR, document)
        required: false
        type: string
      notes:
        description: Additional notes for the assertion (optional)
        required: false
        type: string
      reviewer_name:
        description: Name of the person who approved this badge
        required: false
        type: string
jobs:
  generate-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Generate Badge
      run: "python_args=\"\"\n# Dynamically build argument string from all workflow inputs\nfor input_name in ${{ toJSON(github.event.inputs)\
        \ }}; do\n    input_value=$(echo '${{ toJSON(github.event.inputs) }}' | jq -r --arg key \"$input_name\" '.[$key]')\n\
        \    if [[ -n \"$input_value\" ]]; then\n        python_args=\"$python_args --$input_name \\\"$input_value\\\"\"\n\
        \    fi\ndone\n\nmkdir -p badges_output\neval \"python generate_badge.py $python_args --output-dir badges_output\"\
        \n"
      env: ${{ toJSON(secrets) }}
    - name: Upload Badge as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: open-badge-${{ github.event.inputs.badge_id }}-${{ github.run_id }}
        path: badges_output/
'on':
  workflow_dispatch:
    inputs:
      badge_id:
        description: Select the badge
        required: true
        type: choice
        options:
        - vsre1
      recipient_email:
        description: Recipient's Email
        required: true
        type: string
      expires:
        description: Badge expiration - YYYY-MM-DDTHH:MM:SSZ format (optional)
        required: false
        type: string
        default: ''
      startDate:
        description: Eligibility earned date - YYYY-MM-DDTHH:MM:SSZ format, e.g. 2025-08-28T10:20:00Z
        required: false
        type: string
        default: ''
