# .github/workflows/update-workflow.yml
name: Update Badge System

on:
  push:
    paths:
      - 'badges.yml'
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update workflow and generate issuer files
        run: python update_workflow.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/workflows/generate-badge.yml public/*.json
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Committing..."
            git commit -m "ci: Sync badge system from badges.yml"
            git push
          else
            echo "No changes needed for the badge system."
          fi
